# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aidynbek Mussa | Data Analyst Portfolio
email:
description: >- 
  Portfolio of Aidynbek Mussa – data analyst and economist focused on analytics, systems, and machine learning for impact.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
# Outputting
permalink: /:categories/:title/
paginate: null # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: Aidynbek Mussa
  avatar : "/assets/images/bio-photo.jpg"
  bio: Data analyst and economist turning analytics into action.
  location: New York, NY
  links:
    - label: "aidynbek.mussa@columbia.edu"
      icon: "fas fa-envelope"
      url: "mailto:aidynbek.mussa@columbia.edu"

    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/aidynbekmussa"

    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/aidynbekmussa2000"

    - label: "Telegram"
      icon: "fab fa-telegram"
      url: "https://t.me/aidynthecreator"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
